### ISSUE TITLE
AppName is empty

### ISSUE THREAD

**Issue by gauriaw** [macsux/config-server-buildpack#1]
We followed all the instructions in the README but it is not working. We cloned your code and logged AppName on console that you are reading from AppConfig.Configuration. But it is empty during prestartup (our env variable in PCF/manifest is SPRING__APPLICATION__NAME). Do you have a demo application which is using this buildpack?

our sample app we are using to validate is .net framework 4.7.2

**Comment by macsux** [comment]
Sample provided, however, currently the buildpack is only applicable to Linux stack, though I think it would be a minor change to make it work on windows. I'll test it out and let you know

**Comment by macsux** [comment]
Windows version has been published - this buildpack can now run on both windows and Linux. Note that there are different binaries published for each stack - check the releases page for compiled URL.
